[target.aarch64-linux-android]
linker = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"

[target.armv7-linux-androideabi]
linker = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi26-clang.cmd"

[target.x86_64-linux-android]
linker = "F:/Android_SDk/ndk/29.0.14206865/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android26-clang.cmd"
